import type { Contact } from "@/lib/contacts/types";

export const sampleContacts: Contact[] = [
  {
    id: "jane-smith",
    name: "Jane Smith",
    phone: "+1 (276) 555-0199",
    phoneType: "Mobile",
    email: "jane.smith@email.com",
    group: "Customer",
    tags: ["VIP", "Repeat Buyer"],
    added: "May 19, 2025",
    favorite: false,
    location: "Abingdon, VA",
    lastInteraction: "May 20, 2025",
    notes: "Interested in teacup Chihuahuas. Looking for a female puppy.",
  },
  {
    id: "robert-johnson",
    name: "Robert Johnson",
    phone: "+1 (276) 555-0144",
    phoneType: "Mobile",
    email: "robert.j@email.com",
    group: "Customer",
    tags: ["New"],
    added: "May 18, 2025",
    favorite: false,
    location: "Blacksburg, VA",
    lastInteraction: "May 18, 2025",
    notes: "New contact.",
  },
  {
    id: "emily-davis",
    name: "Emily Davis",
    phone: "+1 (276) 555-0188",
    phoneType: "Mobile",
    email: "emily.davis@email.com",
    group: "Customer",
    tags: ["VIP", "Pickup"],
    added: "May 18, 2025",
    favorite: false,
    location: "Roanoke, VA",
    lastInteraction: "May 18, 2025",
    notes: "Pickup coordination contact.",
  },
  {
    id: "michael-brown",
    name: "Michael Brown",
    phone: "+1 (276) 555-0177",
    phoneType: "Mobile",
    email: "michael.b@email.com",
    group: "Customer",
    tags: ["Repeat Buyer"],
    added: "May 17, 2025",
    favorite: true,
    location: "Bristol, VA",
    lastInteraction: "May 17, 2025",
    notes: "Repeat buyer.",
  },
  {
    id: "sarah-wilson",
    name: "Sarah Wilson",
    phone: "+1 (276) 555-0166",
    phoneType: "Mobile",
    email: "sarah.w@email.com",
    group: "Lead",
    tags: ["Follow Up"],
    added: "May 17, 2025",
    favorite: false,
    location: "Wytheville, VA",
    lastInteraction: "May 17, 2025",
    notes: "Needs follow-up.",
  },
  {
    id: "david-martinez",
    name: "David Martinez",
    phone: "+1 (276) 555-0155",
    phoneType: "Mobile",
    email: "david.m@email.com",
    group: "Supplier",
    tags: ["Breeder"],
    added: "May 16, 2025",
    favorite: false,
    location: "Marion, VA",
    lastInteraction: "May 16, 2025",
    notes: "Breeder supplier contact.",
  },
];
