import {
  Bell,
  Bookmark,
  Bot,
  CalendarClock,
  CircleHelp,
  ClipboardCheck,
  CreditCard,
  FilePenLine,
  Headphones,
  Home,
  KeyRound,
  Link,
  ListChecks,
  LucideIcon,
  Mail,
  MapPin,
  MessageSquare,
  Mic,
  MoreHorizontal,
  PawPrint,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneOff,
  Play,
  Receipt,
  Settings,
  Truck,
  User,
  Users,
  Voicemail,
  Wallet,
  Zap,
} from "lucide-react";

export const iconMap = {
  bell: Bell,
  bookmark: Bookmark,
  bot: Bot,
  "calendar-clock": CalendarClock,
  "circle-help": CircleHelp,
  "clipboard-check": ClipboardCheck,
  "credit-card": CreditCard,
  "file-pen-line": FilePenLine,
  headphones: Headphones,
  home: Home,
  "key-round": KeyRound,
  link: Link,
  "list-checks": ListChecks,
  mail: Mail,
  "map-pin": MapPin,
  "message-square": MessageSquare,
  mic: Mic,
  more: MoreHorizontal,
  "paw-print": PawPrint,
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-off": PhoneOff,
  play: Play,
  receipt: Receipt,
  settings: Settings,
  truck: Truck,
  user: User,
  users: Users,
  voicemail: Voicemail,
  wallet: Wallet,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export function getIcon(name: string): LucideIcon {
  return iconMap[name as keyof typeof iconMap] ?? CircleHelp;
}
